BEGIN;
CREATE TABLE IF NOT EXISTS kiosk_quotes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quote_text TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_kiosk_quotes_quote_text ON kiosk_quotes(quote_text);
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('رسالتك الواضحة تسبق تصميمك الجميل.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى المؤثر… هدف ثم قصة ثم قياس أثر.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تنشر قبل التحقق؛ المصداقية رأس مال.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('جودة الخبر أهم من سرعة الخبر.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('التفاصيل الصغيرة تصنع صورة المؤسسة الكبيرة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل إنجاز يستحق توثيقًا يليق به.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('قِس الأثر… لا تكتفِ بعدّ المشاهدات.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('التصميم يخدم الرسالة، ما يزاحمها.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اختصر النص… وكثّف المعنى.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('عنوان قوي = اهتمام فوري.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('صورة واحدة قد تختصر تقريرًا كاملًا.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('توحيد الهوية البصرية يرفع الثقة تلقائيًا.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الاتساق في الرسائل يقلل الضجيج ويضاعف الفاعلية.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الجمهور أولًا: افهمه قبل أن تخاطبه.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل كل منشور يجيب: ماذا؟ لماذا؟ كيف؟', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الوضوح يسبق البلاغة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('إذا ما قدرت تشرحه ببساطة… راجع الفكرة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل فريق ناجح يبدأ بتوزيع أدوار واضح.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('خطة بدون مؤشرات… كلام جميل فقط.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الأرقام تُقنع إذا رُويت بحكمة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى الموثوق يبني سمعة طويلة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الوثائق تحفظ الإنجاز وتختصر الوقت لاحقًا.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('إنجاز بلا قصة… فرصة ضائعة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('رسائل اليوم تبني ثقة الغد.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تكثر قوالب… وحّدها ثم أبدع داخلها.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اسأل نفسك: هل هذا المحتوى يضيف قيمة؟', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('استجابة سريعة + بيان واضح = إشاعة أقل.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل التواصل مؤسسيًا… لا ارتجاليًا.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('قياس الأثر يبدأ من هدف مكتوب.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل مبادرة تُحكى… تُلهم مبادرات أخرى.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الجودة ليست خيارًا… هي هوية.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى القصير لا يعني محتوى ضعيف.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل الرسالة رحيمة وواضحة ومحترمة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تتنافس على الضجيج… نافس على القيمة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('التكرار الذكي يصنع رسائل ثابتة في الذاكرة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى الناجح: بسيط، صادق، قابل للمشاركة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المنصات تتغير… والرسالة تبقى.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('إن لم توثق اليوم… ستتعب غدًا.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('احكِ الإنجاز بلغة الناس، لا بلغة الملفات.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الجودة تبدأ من أول سطر.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('من حق الجمهور يعرف… ومن واجبنا نوضح.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الشفافية تختصر نصف الأسئلة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الصورة الذهنية تُبنى بالتراكم اليومي.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تنقل معلومة بلا مصدر موثوق.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل المحتوى يحترم عقل المتلقي ووقته.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('سرعة التنفيذ ممتازة… بشرط جودة المراجعة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('فكر في الرحلة كاملة: قبل النشر وأثناءه وبعده.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('التحسين المستمر عادة الفرق الرائدة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('جرّب… قِس… حسّن… ثم كرّر.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('تواصل فعال = خدمة أفضل.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('رؤية 2030 تُلهمنا: أثر، كفاءة، جودة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل رسالة تُسهم في تحقيق مستهدفات الرؤية بروحها.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('التكامل بين الفرق يصنع صورة متماسكة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('البيانات الجيدة تقود قرارًا أسرع.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل التقارير مرئية… فالمرئيات تقنع.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى القيم يسبق المحتوى الرائج.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تترك الإنجاز في الأدراج… أظهره باحتراف.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل لغتك بيضاء… لتصل للجميع.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('الاعتراف بالخطأ بوضوح… يزيد الثقة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('صدق الرسالة يسبق جمال الإخراج.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('ثبات الهوية البصرية = ثبات الثقة.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل دقيقة شاشة… فرصة لتعزيز الصورة الذهنية.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اسأل: ماذا سيستفيد المتلقي بعد 10 ثوانٍ؟', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('لا تكتب للتعبئة… اكتب للتأثير.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('احترام الوقت جزء من احترام الجمهور.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('المحتوى الجيد يترك أثرًا… لا ضجة فقط.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('توثيق اليوم… يوفر عليك تقرير الغد.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('ارفع جودة القصص… ترتفع جودة الانطباع.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('اجعل رسالتك قابلة للقياس.', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO kiosk_quotes (quote_text, is_active, created_at, updated_at) VALUES ('كل منشور: هدف + رسالة + دعوة واضحة.', 1, datetime('now'), datetime('now'));
COMMIT;